<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.kockpit</groupId>
        <artifactId>kockpit-backends</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>kockpit-backend-application</artifactId>
    <properties>
        <java.version>21</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-backend-authentication-basic</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.8.13</version>
        </dependency>
        <!-- applications-side features -->
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-features-heartbeat-service-application</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <!--
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-features-dynaconfig-service-application</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
         -->
        <!-- backend services -->
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-backend-service-search-api</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-backend-service-storage-api</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-features-featureflipping-service-backend</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-features-heartbeat-service-backend</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-features-dynaconfig-service-backend</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <!-- Audits -->
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-audit-web-starter</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.kockpit</groupId>
            <artifactId>kockpit-audit-httpexchange</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>opensearch</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-backend-service-search-opensearch</artifactId>
                    <version>1.0.0-SNAPSHOT</version>
                </dependency>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-backend-service-dashboard</artifactId>
                    <version>1.0.0-SNAPSHOT</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>azure</id>
            <dependencies>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-backend-service-storage-azure</artifactId>
                    <version>1.0.0-SNAPSHOT</version>
                </dependency>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-core-communication-storageaccount</artifactId>
                    <version>1.0.0-SNAPSHOT</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>s3</id>
            <dependencies>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-backend-service-storage-s3</artifactId>
                    <version>1.0.0-SNAPSHOT</version>
                </dependency>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-core-communication-s3</artifactId>
                    <version>1.0.0-SNAPSHOT</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>filesystem</id>
            <dependencies>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-backend-service-storage-filesystem</artifactId>
                    <version>1.0.0-SNAPSHOT</version>
                </dependency>
                <!-- comm -->
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-core-communication-filesystem</artifactId>
                    <version>1.0.0-SNAPSHOT</version>
                </dependency>
            </dependencies>
        </profile>
        <profile>
            <id>kinesis</id>
            <dependencies>
                <dependency>
                    <groupId>org.kockpit</groupId>
                    <artifactId>kockpit-audit-notification-starter-kinesis</artifactId>
                    <version>${project.version}</version>
                </dependency>
            </dependencies>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>org.kockpit.backend.KockpitAuditBackendApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>build-info</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


</project>
